### ISSUE TITLE
Component Todo

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/ezset#53]
- [ ] Addons manage
- [ ] Languages
- [ ] Addon load classes.
- [ ] Frontend override classes.

## New Features

- [ ] Google Webmaster
- [ ] Comments
- [ ] Thumb use lightbox toggle
